### ISSUE TITLE
TextInputController onSubmitted callback doesn't function.

### ISSUE THREAD

**Issue by james-lawrence** [Drakirus/go-flutter-desktop-embedder#12]
havent discovered exactly how this is handled, but its related to #11. 

and the answer is probably related to keyboard handler found in the [google-desktop-embedding](https://github.com/google/flutter-desktop-embedding/blob/master/linux/library/src/internal/keyboard_hook_handler.h)

**Comment by Drakirus** [comment]
I am not sure, but it think the `onSubmitted` callback might be trigger with the keyevents.

**Comment by Drakirus** [comment]
flutter Doc: [TextInputClient.performAction](https://github.com/flutter/flutter/blob/acc591e98bcedafc5c28dcf8e8d86720019d3419/packages/flutter/lib/src/services/system_channels.dart#L140-L142) [TextInputAction.newline](https://github.com/flutter/flutter/blob/2ea1d81cdc5ccb457240b649b49d0ccedbf32794/packages/flutter/lib/src/services/text_input.dart#L299-L314)
The  the newline action is not sended to the Engine.
Related to: https://github.com/flutter/flutter/pull/23015

**Comment by TitouanT** [comment]
The current flutter version used in the project (7.3) doesn't include the fix from  flutter/flutter#23015 https://github.com/flutter/flutter/blob/3b309bda072a6b326e8aa4591a5836af600923ce/packages/flutter/lib/src/widgets/editable_text.dart#L511


I will see if everything works with version 10.1 because it's the first version containing the fix.
see https://github.com/flutter/flutter/blob/v0.10.1/packages/flutter/lib/src/widgets/editable_text.dart#L525

**Comment by Drakirus** [comment]
fixed by #26
