### ISSUE TITLE
How to build the examples?

### ISSUE THREAD

**Issue by jeffmikels** [Drakirus/go-flutter-desktop-embedder#43]
I'm new at Go, but I'm pretty sure I have it installed properly. I'm on Mac Mojave. How do I build the example apps?

**Comment by Drakirus** [comment]
On which step are you stuck?

**Comment by zon7** [comment]
I'm at the same stage. Cannot build stocks. It tells me
"Because stocks depends on flutter_test any from sdk which depends on quiver 2.0.1, quiver 2.0.1 is required.
So, because stocks depends on quiver 2.0.0+1, version solving failed."

I'm using flutter 1.0 and I know I can edit pubspec.yaml, but I want to solve it right :)

**Comment by Drakirus** [comment]
Ohh, The stocks example is kinda old. 😅

I you want the latest stocks example, please download it from [the official flutter repo](https://github.com/flutter/flutter/tree/master/examples/stocks).

Also you need to read [this README.md](https://github.com/Drakirus/go-flutter-desktop-embedder/blob/master/example/stocks/flutter_project/stocks/README.md) in order to make the appropriate adaptation.

**Comment by jeffmikels** [comment]
> On which step are you stuck?

Step 0. I don't know where to start.

I have go installed.
I have downloaded this repo.
I already have flutter installed in its default location.

I know enough to try `go build` but that doesn't work.
So I'm simply asking "Where do I start?"

**Comment by jeffmikels** [comment]
Oh! Never mind... apparently the README has a little arrow next to the Operating system that shows build instructions when you click on the OS. I've never seen that before on a Github README.
