### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gedw99** [Drakirus/go-flutter-desktop-embedder#56]

**Comment by gedw99** [comment]
Btw are you sure you want GNU license ? Slot of people will want to use this for commercial projects

**Comment by Drakirus** [comment]
CI is starting to become necessary, unfortunately, I don't have the time atm.

Regarding the license, it's an LGPL license which allows for Commercial use.

**Comment by Drakirus** [comment]
according to Gustavo Niemeyer (Cannoncial, gopkg.in)
> The text of the LGPLv3 is very clear in that regard: only shared
linkage is accepted if you intend to use a different license in the
rest of the code, which excludes the way Go links them.

> At Canonical we're talking to our lawyers right now and are writing
down a specific exception for all of the Go-related libraries exactly
because of that (there's no intention to force linked packages to buy
into the same license).

**Comment by Drakirus** [comment]
After chatting a bit with @GeertJohan, we concluded that BSD was more appropriated.
